### ISSUE TITLE
リンクが切れていました

### ISSUE THREAD

**Issue by kanpapa** [AI-Robot-Book/chapter5#1]
https://github.com/AI-Robot-Book/chapter5/blob/main/yolov5_ros2/README.md のインストールのところ、

・opencv_ros2のインストール作業

 のリンクが切れていました。

現在
https://github.com/AI-Robot-Book/chapter5/blob/main/yolov5_ros2/opencv_ros2

正しくは
https://github.com/AI-Robot-Book/chapter5/blob/main/opencv_ros2

**Comment by y-masutani** [comment]
ご指摘ありがとうございます。修正しました。
https://github.com/AI-Robot-Book/chapter5/commit/875830158594c8bd5874d76f18b650474753682f
